version: '3.9'

services:
  database:
    image: postgis/postgis:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: authentication
      POSTGRES_PASSWORD: authentication
      POSTGRES_DB: authentication

volumes:
  psql-data:
